"""Typed project model (pydantic)."""

from budget_core.model.base import BudgetModel, Sourced
from budget_core.model.config import (
    AttenuationEntry,
    AttenuationTable,
    Ebn0Entry,
    Ebn0Table,
    MarginPolicy,
    MaturityClass,
    PowerConfig,
)
from budget_core.model.environment import (
    Elements,
    GroundSite,
    GroundStation,
    Orbit,
    Scenario,
    ScenarioRule,
    ScenarioSegment,
    Target,
)
from budget_core.model.equipment import (
    Bus,
    PowerMode,
    Spacecraft,
    SpacecraftMode,
    TemperatureLimits,
    Unit,
)
from budget_core.model.mass import (
    Expendable,
    Inertia,
    MassLimit,
    MassLimits,
    MassProperties,
    inertia_is_physical,
)
from budget_core.model.power_system import (
    ArrayFace,
    Attitude,
    Battery,
    PowerLimits,
    PowerSystem,
    SolarArray,
)
from budget_core.model.project import Project, ProjectConfig, ProjectMeta
from budget_core.model.thermal import (
    Conductance,
    Exposure,
    Surface,
    ThermalCase,
    ThermalEnvironment,
    ThermalModel,
    ThermalNode,
)
from budget_core.model.versions import CURRENT_VERSIONS

__all__ = [
    "CURRENT_VERSIONS",
    "AttenuationEntry",
    "ArrayFace",
    "AttenuationTable",
    "Attitude",
    "Battery",
    "BudgetModel",
    "Bus",
    "Conductance",
    "Exposure",
    "Ebn0Entry",
    "Elements",
    "GroundSite",
    "GroundStation",
    "Orbit",
    "Scenario",
    "ScenarioRule",
    "ScenarioSegment",
    "Target",
    "Ebn0Table",
    "Expendable",
    "Inertia",
    "MassLimit",
    "MassLimits",
    "MassProperties",
    "MarginPolicy",
    "MaturityClass",
    "PowerConfig",
    "PowerLimits",
    "PowerMode",
    "PowerSystem",
    "Project",
    "ProjectConfig",
    "ProjectMeta",
    "SolarArray",
    "Sourced",
    "Surface",
    "TemperatureLimits",
    "ThermalCase",
    "ThermalEnvironment",
    "ThermalModel",
    "ThermalNode",
    "Spacecraft",
    "SpacecraftMode",
    "Unit",
    "inertia_is_physical",
]
